import { useCallback, useEffect, useState } from 'react';
import { api, useAction, Shell, Hero, Glass, Heading, ErrorBox, Tag, Checks, Evidence, CatalogView, stamp, short, display, download, ArrowUpRight, ArrowDownToLine } from './ui';
import type { Catalog, CheckItem } from './ui';
type Observation = {schema:string;mode:string;issued_at:string;provider:{id:string;name:string;url:string|null};latency_ms:number;accepted:boolean;decision:string;checks:CheckItem[];receipt_hash:string;recorded_at?:string;snapshot:unknown;collection_error?:{message:string}|null;injected?:boolean};
type Run={schema:string;mode:string;issued_at:string;selected_provider:string|null;decision:string;attempts:Observation[];checks:CheckItem[];receipt_hash:string;limitations:string[]};
type Review={source:'llm'|'rule_fallback';configured:boolean;model:string|null;verdict:'accepted'|'rejected'|'uncertain';rationale:string;cited_check_ids:string[];grounded:boolean;note:string;deterministic_verdict:string};
type ProviderStat={id:string;name:string;total:number;accepted:number;rejected:number;acceptance_rate:number|null;average_latency_ms:number|null;last_observed_at:string};
type Records={scope:string;records:(Observation & {receipt:Observation})[];stats:{total:number;accepted:number;rejected:number;providers:ProviderStat[]};limitations:string[]};
export default function App(){
 const [catalog,setCatalog]=useState<Catalog>();const [catalogError,setCatalogError]=useState('');const [records,setRecords]=useState<Records>();const [recordsError,setRecordsError]=useState('');const [provider,setProvider]=useState('auto');const [inject,setInject]=useState(false);const probe=useAction<Run>();const demo=useAction<Run>();const [evidence,setEvidence]=useState<Run>();const [review,setReview]=useState<Review>();
 useEffect(()=>{const controller=new AbortController();api<Catalog>('catalog',undefined,controller.signal).then(setCatalog).catch(e=>{if(!controller.signal.aborted)setCatalogError(String(e.message));});return()=>controller.abort();},[]);
 const refresh=useCallback(async()=>{setRecordsError('');try{setRecords(await api<Records>('records'));}catch(e){setRecordsError(e instanceof Error?e.message:'服务记录暂时不可用');}},[]);
 useEffect(()=>{void refresh();},[refresh]);
 async function reviewOf(result:Run){try{setReview(await api<Review>('review',{receipt:result}));}catch{setReview(undefined);}}
 async function runLive(){setEvidence(undefined);setReview(undefined);const result=await probe.run('probe',{provider_id:provider,...(inject?{inject:'stale'}:{})});if(result){setEvidence(result);void reviewOf(result);void refresh();}}
 async function runDemo(scenario:string){setEvidence(undefined);setReview(undefined);const result=await demo.run('demo',{scenario});if(result){setEvidence(result);void reviewOf(result);}}
 const busy=probe.busy||demo.busy;
 return <Shell kind="trust" busy={busy}><Hero number="01" title="调用之前，先验真。" em="把服务表现，留成证据。" description="给研究 Agent、工具开发者和服务使用者：检查陌生数据服务的当前交付，把通过与拒收的依据变成下一位使用者可查的记录。" steps={['选择服务','检查交付','记录表现','独立复核']}/>
 <Glass className="work-card" id="workbench"><Heading kicker="LIVE / 服务探测" title="它现在，能交付吗？"><Tag>Ethereum · 公开只读</Tag></Heading><div className="form-grid"><label>待验收的数据服务<select value={provider} disabled={busy} onChange={e=>setProvider(e.target.value)}><option value="auto">自动选择 · 按可用服务顺序验收</option>{catalog?.providers?.map(p=><option value={display(p.id)} disabled={!p.enabled} key={display(p.id)}>{display(p.name)}{p.enabled?'':' · 暂未启用'}</option>)}</select></label><button className="primary" disabled={busy||!catalog} onClick={()=>void runLive()}>{probe.busy?'正在读取并验收…':'执行真实探测'}<ArrowUpRight size={16}/></button></div><label className="inject-toggle"><input type="checkbox" checked={inject} disabled={busy} onChange={e=>setInject(e.target.checked)}/>故障注入 · 模拟首个服务返回过期区块（明确标注，用于演示拒收→自动切换）</label><p className="form-note">实时查询固定公共 RPC，校验网络、最终确认区块和关联回执。结果来自本次请求，不使用历史评分代替当前检查。</p><div className="provider-list">{catalog?.providers?.map(p=><div className="provider" key={display(p.id)}><div><strong>{display(p.name)}</strong><Tag>{p.enabled?'允许探测':'未启用'}</Tag></div><p>{display(p.url)}</p>{!p.enabled&&<p>{display(p.disabled_reason||p.reason||'来源待核验；不参与自动选择。')}</p>}</div>)}</div><ErrorBox error={catalogError||probe.error}/></Glass>
 {probe.data&&<Result data={probe.data} review={review}/>}<section className="records-section" id="records"><Heading kicker="PUBLIC OBSERVATIONS / 公开观测" title="让下一次选择，有据可循。"><button className="secondary" onClick={()=>void refresh()}>刷新记录</button></Heading><p className="muted">本实例的真实服务观测，按服务、快照、规则版本与验收结果去重。这里展示样本和结果，不把单站统计当作跨主体信誉。</p><ErrorBox error={recordsError}/>{records&&<><div className="metrics"><div className="metric"><span>独立观测样本</span><strong>{records.stats.total}<small>次</small></strong><p>同快照同结果不重复计数</p></div><div className="metric"><span>交付验收通过</span><strong>{records.stats.accepted}<small>次</small></strong><p>通过不代表服务永久可靠</p></div><div className="metric"><span>未通过 / 读取失败</span><strong>{records.stats.rejected}<small>次</small></strong><p>失败原因同样保留</p></div></div><div className="table-wrap"><table><caption className="file-input">各服务在本实例的观测样本</caption><thead><tr><th>服务</th><th>样本分母</th><th>通过 / 未通过</th><th>平均读取耗时</th><th>最近观测</th></tr></thead><tbody>{records.stats.providers.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.total}</td><td>{p.accepted} / {p.rejected}</td><td>{p.average_latency_ms===null?'—':`${Math.round(p.average_latency_ms)} ms`}</td><td>{stamp(p.last_observed_at)}</td></tr>)}</tbody></table>{records.stats.total===0&&<p className="empty">还没有真实观测。执行一次服务探测后，这里会显示结果。</p>}</div><details className="raw"><summary>查看最近 {records.records.length} 条可复核记录</summary><div className="table-wrap"><table><thead><tr><th>时间 / 服务</th><th>结果</th><th>证据摘要</th><th>复用</th></tr></thead><tbody>{records.records.map((r,i)=><tr key={`${r.receipt_hash}-${i}`}><td>{r.provider.name}<small>{stamp(r.issued_at)}</small></td><td><Tag pass={r.accepted}>{r.accepted?'通过':'未通过'}</Tag></td><td className="mono" title={r.receipt_hash}>{short(r.receipt_hash)}</td><td><button className="text-link" onClick={()=>download(`服务观测-${r.receipt_hash.slice(0,10)}.json`,r.receipt)}>下载回执 <ArrowDownToLine size={14}/></button></td></tr>)}</tbody></table></div></details></>}</section>
 <section className="lab-section"><Heading kicker="SANDBOX / 规则实验" title="故意给它一份坏数据。"><Tag>合成数据 · 不计入真实记录</Tag></Heading><p className="muted">体验数据过期或交付缺项时如何拒收，再检查合格输出。这些实验使用固定合成数据，仅用于验证验收规则。</p><div className="actions"><button className="secondary" disabled={busy} onClick={()=>void runDemo('stale')}>过期资料 → 拒收</button><button className="secondary" disabled={busy} onClick={()=>void runDemo('missing')}>缺少回执 → 拒收</button><button className="secondary" disabled={busy} onClick={()=>void runDemo('healthy')}>完整交付 → 验收</button></div><ErrorBox error={demo.error}/>{demo.data&&<Result data={demo.data} review={review}/>}</section>
 <Evidence receipt={evidence} name="江城验真-服务验收"/><CatalogView catalog={catalog} error={catalogError}/><section className="method-section"><Heading kicker="PUBLIC GOOD / 开放方法" title="公开依据，不制造一个神秘评分。"/><div className="info-columns"><div><h3>现在能用</h3><p>固定来源探测、版本化验收规则、去重观测记录、摘要下载与离线规则重放。真实读取失败也进入可查看的记录。</p><p>记录由本实例生成；公开内容仅包含公共链来源和工具结果，不收集私钥或业务资料。</p></div><div><h3>明确的下一步</h3><p>跨主体身份签名、独立验证者、申诉处理与链上信誉尚未接入。当前没有抵御女巫攻击的可信身份系统。</p><p>原始规则可复用，服务选择保留样本量、时效和失败依据，不能据少量样本推导服务的总体质量。</p></div></div></section></Shell>;
}
function Result({data,review}:{data:Run;review?:Review}){const accepted=data.decision==='accepted';return <section className="result-card" aria-live="polite"><div className="result-head"><div><Tag>{data.mode==='live'?'实际 RPC 观测':'合成规则实验'}</Tag><h3>{accepted?'本次交付满足验收条件。':'本次交付未通过验收。'}</h3><p>{stamp(data.issued_at)} · {data.attempts.length} 次服务尝试{data.attempts.some(a=>a.injected)&&' · 含故障注入（模拟）'}</p></div><Tag pass={accepted}>{accepted?'可供本次任务使用':'停止交接'}</Tag></div><Checks items={data.checks}/>{review&&<div className="review-card"><div className="review-head"><Tag pass={review.verdict==='accepted'?true:review.verdict==='rejected'?false:undefined}>{review.verdict==='accepted'?'语义验收：通过':review.verdict==='rejected'?'语义验收：拒收':'语义验收：存疑'}</Tag><Tag>{review.source==='llm'?`LLM · ${review.model||''}`:'确定性回退'}</Tag></div><p>{review.rationale}</p><div className="review-cites">{review.cited_check_ids.map(id=><span className="mono" key={id}>#{id}</span>)}</div><small>{review.grounded?'结论与确定性证据一致':`与确定性证据不一致，已以证据为准（确定性结论 ${review.deterministic_verdict}）`} · {review.note}</small></div>}{data.attempts.length>1&&data.attempts.map((a,i)=><details className="attempt" key={`${a.provider.id}-${i}`}><summary><span>尝试 {i+1} · {a.provider.name}{a.injected?' · 故障注入（模拟过期）':''}</span><Tag pass={a.accepted}>{a.accepted?'通过':'拒收'}</Tag></summary><Checks items={a.checks}/></details>)}<p className="provenance">证据摘要 <code>{data.receipt_hash}</code></p></section>;}
